# 0. Imports

In [ ]:
from google.colab import drive
import pandas as pd

# 1. Mount Drive and retrieve excel data

In [ ]:
drive.mount("/content/drive/")
project_path = "/content/drive/MyDrive/CLW Ancient Management System"
dataset = f"{project_path}/Liste des Anciens CLW 1978-2021 - Final Database.xlsx"

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

# 2. Exctract excel data and place into pandas dataframe

In [ ]:
df = pd.read_excel(dataset)
df.head(2)

,Unnamed: 0,Promo,Nom,Prénom,Email,Email 2,ID#,Promo.1,Année Sortie,Classe Sortie,...,test,Unsubscribe,Unsubscribe (Number of Times),Consentement (Autorisation) Perso,Consentement (Autorisation) Educ.,Consentement (Autorisation) Prof.,LINKEDIN Annonce on 12.04.2019,Lettre de Solidarité envoyé le 17.04.2019 - opened by Alumni,Lettre Startups envoyé le 24.05.2019 - opened by Alumni,Startup Talk - 12.06.2019 - Did not open as of 09.06.2019 @ 12PM
0,1.0,1978.0,Ali Ahmad,Rania,dariadaniel@yahoo.com,rania@crestinv.com,1781002.0,1978.0,1976.0,2nde,...,0.0,NaN,NaN,NaN,NaN,NaN,-,Read,-,Read
1,2.0,1978.0,Atyah,Manal,mana-mou@live.com,manal.abiabdallah@gmail.com,1780001.0,1978.0,1978.0,T,...,0.0,NaN,NaN,NaN,NaN,NaN,Read,Read,Read,-

#3. Fix up Headers to Match Wordpress CSV Guidelines

### The headers should match the Alumni Platform file in the drive. What isn't present there should be removed and what is named differently should be renamed.

Commands to use are:
- df.rename( columns = { 'old name' : 'new name' }, inplace = True)
- df.drop( [ 'column name' ], axis = 1)

In [ ]:
df.rename( columns={'Unnamed: 0':'Sorting Number'}, inplace=True )
df.head(2)

,Sorting Number,Promo,Nom,Prénom,Email,Email 2,ID#,Promo.1,Année Sortie,Classe Sortie,...,test,Unsubscribe,Unsubscribe (Number of Times),Consentement (Autorisation) Perso,Consentement (Autorisation) Educ.,Consentement (Autorisation) Prof.,LINKEDIN Annonce on 12.04.2019,Lettre de Solidarité envoyé le 17.04.2019 - opened by Alumni,Lettre Startups envoyé le 24.05.2019 - opened by Alumni,Startup Talk - 12.06.2019 - Did not open as of 09.06.2019 @ 12PM
0,1.0,1978.0,Ali Ahmad,Rania,dariadaniel@yahoo.com,rania@crestinv.com,1781002.0,1978.0,1976.0,2nde,...,0.0,NaN,NaN,NaN,NaN,NaN,-,Read,-,Read
1,2.0,1978.0,Atyah,Manal,mana-mou@live.com,manal.abiabdallah@gmail.com,1780001.0,1978.0,1978.0,T,...,0.0,NaN,NaN,NaN,NaN,NaN,Read,Read,Read,-